version: '3.7'

services:
  postgres_bd:
    image: postgres
    container_name: products_app
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=products
    volumes:
      - pgdata:/data/postgres

  redis_bd:
    image: 'redis:alpine'
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - rsdata:/data/rd

  app:
    build: .
    container_name: node
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - postgres_bd
      - redis_bd

volumes:
  pgdata:
    driver: local
  rsdata:
    driver: local
